## K-Means

- **Q1** Se tiene que implementar un algoritmo K-Means siguiendo los pasos del pseudo código

In [1]:
# Añaden las librerias para el proyecto

# Import para el numpy
import numpy as np

# Librería para los Plots
import matplotlib.pyplot as plt

Implementación del algoritmo de k-Means

In [2]:
# Q1.- Esta es mi implementación del algoritmo K-Means

# Algoritmo K-Means
def kMeans(X, K, Iter_max):
    # Se inicializa el valor de los centroides cogiendo 3 valores aleatorios dentro del dataset 
    # que se proporciona.
    centroide = X[np.random.choice(np.arange(len(X)), K), :]
    # Se crea una matriz del mismo orden del centroide para compararla y así poder detectar cuando
    # el sistema converge.
    centroide_old = np.zeros([K,len(X)])
    # Variables de control de convergencia
    converge = False
    iteracion = 0;
    # Se inicializa un bucle de convergencia. Se irá ejecutando hasta que se llegue al máximo número
    # de iteraciones o cuando el valor actual sea igual al valor anterior, lo que querrá decir que el 
    # valor es el mejor que se puede encontrar.
    while converge == False:
        # Realizo un código para asignar el centroide más cercano a cada punto
        ## Primero me recorro todo el dataset
        C_1 = [] # Valor para calcular los indices del centroide
        for data in X:
            # Se compara el punto con los valores del centroide para obtener el valor más cercano
            C_temp = []
            for cent in centroide:
                C_temp.append(np.dot(data-cent,data-cent))
            # Se asigna a la posición del centroide más cercano
            C_1.append(np.argmin(C_temp))
        C = np.array(C_1) # Valores transformados a array
        # Se recalculan los valores del centroide, realizando una media de todos los valores de 
        # cercanos a cada punto.
        centroide = [X[C == k].mean(axis = 0) for k in range(K)]
        # Se sale del bucle si las variables han convergido, es decir, si se ha llegado
        # al máximo de iteraciones o la variable encontrada es igual a la anterior
        if (iteracion == Iter_max) or (np.array_equal(centroide,centroide_old)):
            converge = True
        else:
            iteracion += 1
            centroide_old = centroide
    # La función devuelve le centroide, el array C con los indices y el número de iteraciones que
    # se han tenido que hacer para llegar al resultado óptimo, o el máximo si no se ha llegado hasta 
    # el final o no se ha llegado
    return np.array(centroide) , C, iteracion

- **Q2** Probar el algoritmo K-Means realizado con K = 3 y con las dos primeras dimensiones del dataset iris. para despues ir probandolo con 3 y 4.

In [3]:
# Se cargan los datos del archivo data.iris
data_Iris = np.array([map(float,x.split(',')[:-1]) for x in open('iris.data') if x.strip()])

# Se crean las variables para 2 y 3 columnas

## 2 columnas
data_Iris_2 = data_Iris[:,:2]

In [4]:
# Se inicializan las variables del bucle

## Se asignan el conjunto de datos con dos columnas
X = data_Iris_2

## Se inicializa la K a 3
K = 3

## Se definen el numero maximo de iteraciones como 100
iteraciones = 100

# Se ejecuta el algoritmo K-Means
centroides, C, iteraciones = kMeans(X, K, iteraciones)

# Se dibujan los resultados en un plot
plt.title("Q2.- K-Means Iris data Accuracy 2 parameters")
plt.xlabel("Longitud del sepalo")
plt.ylabel("Anchura del sepalo")

# Se agregan al plot los puntos de distintos colores, dependiendo del centroide al que
# han sido asignados
plt.plot(X[C == 0, 0], X[C == 0, 1], 'ob',
         X[C == 1, 0], X[C == 1, 1], 'or',
         X[C == 2, 0], X[C == 2, 1], 'og')

# Se agregan las posiciones de los tres centroides
plt.plot(centroides[:,0],centroides[:,1],'*y',markersize=20)

# Se dibuja el plot
plt.draw()

# Resultado del Q2 para un dataset de 2 columnas
print 'Q2.- Para el dataset de 2 columnas, se ha obtenido en ', iteraciones, ' los siguientes centroides:\n'
print centroides
print '\nQ2.- En el plot los puntos redondos son los valores del data set y las estrellas amarillas los centroides.'

Q2.- Para el dataset de 2 columnas, se ha obtenido en  4  los siguientes centroides:

[[ 6.81276596  3.07446809]
 [ 5.77358491  2.69245283]
 [ 5.006       3.418     ]]

Q2.- En el plot los puntos redondos son los valores del data set y las estrellas amarillas los centroides.


In [5]:
# Se define una función para calcular el MSE
# El calculo del MSE para 2 columnas es
# MSE = (Suma distancias en rango 1)² + (suma distancias en rango 2)²/(numero de filas * numero columnas)
def MSE_Centroide(Y,X):
    Rango = Y.shape[1]
    # Se crea una variable el valor del centroide de la misma longitud que Y
    X_Full = np.empty([len(Y),Rango])
    # Rellenar con los valores del centroide
    for i in range(len(X_Full)):
        X_Full[i] = X
    MSE = 0
    # Se calcula el MSE en todas las columnas y se suma
    for i in range(Rango):
        MSE += sum((Y[:,i]-X_Full[:,i])**2) / len(Y)
    # Se devuelve el valor dividido por el número de columnas
    return MSE / Rango

def MSE_Total(Y,X):
    MSE = 0
    # Se calcula el MSE en todas las columnas y se suma
    for i in range(Y.shape[1]):
        MSE += sum((Y[:,i]-X[:,i])**2) / len(Y)
    # Se devuelve el valor dividido por el número de columnas
    return MSE / Y.shape[1]

# Resultados para el calculo del primer MSE
print 'Q2.- Se calculan los MSE para el dataset de 2 parametros\n'

# Se calcula el MSE para el primer Centroide
MSE_2C_1 = MSE_Centroide(X[C==0], centroides[0])
print 'Q2.- El MSE del primer centroide es: ', MSE_2C_1

MSE_2C_2 = MSE_Centroide(X[C==1], centroides[1])
print 'Q2.- El MSE del segundo centroide es: ', MSE_2C_2

MSE_2C_3 = MSE_Centroide(X[C==2], centroides[2])
print 'Q2.- El MSE del tercer centroide es: ', MSE_2C_3

# Para calcular el MSE global, se debe crear un array con los valores del centroide
# en la fila que toquen
X_Total = np.empty([len(X),X.shape[1]])
for i in range(len(X_Total)):
    X_Total[i] = centroides[C[i]]

MSE_2C_Total = MSE_Total(X, X_Total)
print 'Q2.- El MSE total para un dataset de 2 parametros es:', MSE_2C_Total
print '\n'

Q2.- Se calculan los MSE para el dataset de 2 parametros

Q2.- El MSE del primer centroide es:  0.13427342689
Q2.- El MSE del segundo centroide es:  0.106603773585
Q2.- El MSE del tercer centroide es:  0.13202
Q2.- El MSE total para un dataset de 2 parametros es: 0.123745673759




Ahora, para comprobar como de buenas han sido los centroides, se calcula la diferencia entre lo calculado y la media de los valores en cada grupo

In [6]:
# Se comienza calculando la media de los valores, para saber en que posición esta el centro
print 'Q2.- Se calculan las distancias con los valores centrales calculados para el dataset de 2 parametros\n'

## Comienzo por el primer centroide
X1_2C_Center = sum(X[C==0])/len(X[C==0])

print 'Q2.-\tEl valor del primer centroide es ', centroides[0]
print '\tEl centro calculado es ', X1_2C_Center
print '\ty la diferencia es ', X1_2C_Center - centroides[0]

## Segundo centroide centroide
X2_2C_Center = sum(X[C==1])/len(X[C==1])

print '\nQ2.-\tEl valor del segundo centroide es ', centroides[1]
print '\tEl centro calculado es ', X2_2C_Center
print '\ty la diferencia es ', X2_2C_Center - centroides[1]

## Por último el tercer centroide
X3_2C_Center = sum(X[C==2])/len(X[C==2])

print '\nQ2.-\tEl valor del tercer centroide es ', centroides[2]
print '\tEl centro calculado es ', X3_2C_Center
print '\ty la diferencia es ', X3_2C_Center - centroides[2]


Q2.- Se calculan las distancias con los valores centrales calculados para el dataset de 2 parametros

Q2.-	El valor del primer centroide es  [ 6.81276596  3.07446809]
	El centro calculado es  [ 6.81276596  3.07446809]
	y la diferencia es  [ 0.  0.]

Q2.-	El valor del segundo centroide es  [ 5.77358491  2.69245283]
	El centro calculado es  [ 5.77358491  2.69245283]
	y la diferencia es  [ 0.  0.]

Q2.-	El valor del tercer centroide es  [ 5.006  3.418]
	El centro calculado es  [ 5.006  3.418]
	y la diferencia es  [ 0.  0.]


In [7]:
print 'Q2.- Como se puede ver la predicción y el cálculo es igual, por tanto la predición es muy buena'

Q2.- Como se puede ver la predicción y el cálculo es igual, por tanto la predición es muy buena


Se repite todo para el conjunto de datos completo.

In [8]:
# Se inicializan las variables del bucle

## Se asignan el conjunto de datos con dos columnas
X = data_Iris

## Se inicializa la K a 3
K = 3

## Se definen el numero maximo de iteraciones como 100
iteraciones = 100

# Se ejecuta el algoritmo K-Means
centroides, C, iteraciones = kMeans(X, K, iteraciones)

# Resultado del Q2 para un dataset de 2 columnas
print 'Q2.- Para el data set completo se ha obtenido en ', iteraciones, ' los siguientes centroides:\n'
print centroides

Q2.- Para el data set completo se ha obtenido en  4  los siguientes centroides:

[[ 5.9016129   2.7483871   4.39354839  1.43387097]
 [ 5.006       3.418       1.464       0.244     ]
 [ 6.85        3.07368421  5.74210526  2.07105263]]


In [9]:
# Se calcula el MSE para el dataset completo para los 4 valores y el total

# Resultados para el calculo del primer MSE
print 'Q2.- Se calculan los MSE para el dataset completo\n'
# Se calcula el MSE para el primer Centroide
MSE_1 = MSE_Centroide(X[C==0], centroides[0])
print 'Q2.- El MSE del primer centroide es: ', MSE_1

MSE_2 = MSE_Centroide(X[C==1], centroides[1])
print 'Q2.- El MSE del segundo centroide es: ', MSE_2

MSE_3 = MSE_Centroide(X[C==2], centroides[2])
print 'Q2.- El MSE del tercer centroide es: ', MSE_3

# Para calcular el MSE global, se debe crear un array con los valores del centroide
# en la fila que toquen
X_Total = np.empty([len(X),X.shape[1]])
for i in range(len(X_Total)):
    X_Total[i] = centroides[C[i]]

MSE_Total = MSE_Total(X, X_Total)
print 'Q2.- El MSE total para un dataset completo es:', MSE_Total
print '\n'

Q2.- Se calculan los MSE para el dataset completo

Q2.- El MSE del primer centroide es:  0.160568418314
Q2.- El MSE del segundo centroide es:  0.076202
Q2.- El MSE del tercer centroide es:  0.157101800554
Q2.- El MSE total para un dataset completo es: 0.131568069044




In [10]:
# Se vuelve a calcular la distancia con la media de valores, en este caso para el dataset completo
print 'Q2.- Se calculan las distancias con los valores centrales calculados para el dataset completo\n'
## Comienzo por el primer centroide
X1_Center = sum(X[C==0])/len(X[C==0])

print 'Q2.-\tEl valor del primer centroide es ', centroides[0]
print '\tEl centro calculado es ', X1_Center
print '\ty la diferencia es ', X1_Center - centroides[0]

## Segundo centroide centroide
X2_Center = sum(X[C==1])/len(X[C==1])

print '\nQ2.-\tEl valor del segundo centroide es ', centroides[1]
print '\tEl centro calculado es ', X2_Center
print '\ty la diferencia es ', X2_Center - centroides[1]

## Por último el tercer centroide
X3_Center = sum(X[C==2])/len(X[C==2])

print '\nQ2.-\tEl valor del tercer centroide es ', centroides[2]
print '\tEl centro calculado es ', X3_Center
print '\ty la diferencia es ', X3_Center - centroides[2]

Q2.- Se calculan las distancias con los valores centrales calculados para el dataset completo

Q2.-	El valor del primer centroide es  [ 5.9016129   2.7483871   4.39354839  1.43387097]
	El centro calculado es  [ 5.9016129   2.7483871   4.39354839  1.43387097]
	y la diferencia es  [ 0.  0.  0.  0.]

Q2.-	El valor del segundo centroide es  [ 5.006  3.418  1.464  0.244]
	El centro calculado es  [ 5.006  3.418  1.464  0.244]
	y la diferencia es  [ 0.  0.  0.  0.]

Q2.-	El valor del tercer centroide es  [ 6.85        3.07368421  5.74210526  2.07105263]
	El centro calculado es  [ 6.85        3.07368421  5.74210526  2.07105263]
	y la diferencia es  [ 0.  0.  0.  0.]


In [11]:
print 'Q2.- Como el anterior caso, la predicción es muy buena, aparece sin error.'

Q2.- Como el anterior caso, la predicción es muy buena, aparece sin error.
